wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/simclr_sleepedf/ts_main.py
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.12
    start_time: 1656235486
    t:
      1:
      - 1
      - 5
      - 11
      3:
      - 13
      4: 3.8.12
      5: 0.12.9
      6: 4.11.3
      8:
      - 2
      - 5
